//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts_Categories
    {
        public long id { get; set; }
        public long account_id { get; set; }
        public int category_id { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual catalog_categories catalog_categories { get; set; }
    }
}
