//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Messages
    {
        public long id { get; set; }
        public string message { get; set; }
        public int type_id { get; set; }
        public string user_id { get; set; }
        public long account_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string guid { get; set; }
    
        public virtual Account_MessagesTypesHB Account_MessagesTypesHB { get; set; }
        public virtual Accounts Accounts { get; set; }
    }
}
