//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts_Roles
    {
        public int Id { get; set; }
        public long Account { get; set; }
        public int Role { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Accounts_RolesHB Accounts_RolesHB { get; set; }
    }
}
