//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts_Moderation
    {
        public int id { get; set; }
        public Nullable<long> account_id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string GuId { get; set; }
        public Nullable<int> ChatId { get; set; }
    
        public virtual Accounts Accounts { get; set; }
    }
}
