//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounts()
        {
            this.C100tx_Orders = new HashSet<C100tx_Orders>();
            this.Accounts_Roles = new HashSet<Accounts_Roles>();
            this.Accounts_Users = new HashSet<Accounts_Users>();
            this.Logs = new HashSet<Logs>();
            this.Projects = new HashSet<Projects>();
        }
    
        public long Id { get; set; }
        public string ShortLegalName { get; set; }
        public string FullLegalName { get; set; }
        public string INN { get; set; }
        public string DirectorFullName { get; set; }
        public string ContactName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Site { get; set; }
        public Nullable<int> Industry { get; set; }
        public string Actual_Street { get; set; }
        public string Legal_Street { get; set; }
        public string Bank_Bic { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Account { get; set; }
        public string Bank_Korrespondent { get; set; }
        public string KPP { get; set; }
        public Nullable<System.Guid> ClientGuid { get; set; }
        public string NumberContract { get; set; }
        public Nullable<System.DateTime> DateContract { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public string Ogrn { get; set; }
        public string PostDirector { get; set; }
        public string PostContact { get; set; }
        public string Document { get; set; }
        public string Interaction { get; set; }
        public Nullable<System.DateTime> dateadd { get; set; }
        public Nullable<bool> NDS_YES { get; set; }
        public Nullable<bool> NDS_NO { get; set; }
        public Nullable<bool> ZAKUPKI_YES { get; set; }
        public Nullable<bool> ZAKUPKI_NO { get; set; }
        public string SKLAD_ADDRESS { get; set; }
        public string KPTextBlock { get; set; }
        public string Currency { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C100tx_Orders> C100tx_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounts_Roles> Accounts_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounts_Users> Accounts_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logs> Logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
