//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aceess_Roles
    {
        public int id { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<int> accessId { get; set; }
        public Nullable<int> tableId { get; set; }
        public Nullable<int> menuId { get; set; }
    
        public virtual Aceess_TypeHB Aceess_TypeHB { get; set; }
        public virtual Functions Functions { get; set; }
        public virtual Tables Tables { get; set; }
    }
}
