//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aceess_Users
    {
        public int id { get; set; }
        public string userId { get; set; }
        public Nullable<int> accessId { get; set; }
    
        public virtual Aceess_TypeHB Aceess_TypeHB { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
