//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aleks_daspecs_goodstbl
    {
        public long id { get; set; }
        public Nullable<long> src_id { get; set; }
        public long parent { get; set; }
        public long spec_id { get; set; }
        public long line_id { get; set; }
        public long good_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string provider { get; set; }
        public string manufacturer { get; set; }
        public long count { get; set; }
        public long units { get; set; }
        public long price { get; set; }
        public string currency { get; set; }
        public string @params { get; set; }
        public string comment { get; set; }
        public Nullable<decimal> markup { get; set; }
        public string mongo_image_id { get; set; }
        public byte is_cheated { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> volume { get; set; }
        public Nullable<long> provider_id { get; set; }
        public Nullable<int> approved_by_provider { get; set; }
        public Nullable<int> good_parent_id { get; set; }
        public Nullable<long> delivery { get; set; }
        public string deliveryErrors { get; set; }
    }
}
