//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aleks_goods_providers_log
    {
        public Nullable<int> id { get; set; }
        public int good_id { get; set; }
        public int prov_id { get; set; }
        public Nullable<System.DateTime> deletedon { get; set; }
    }
}
