//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aleks_goods_moderate
    {
        public int good_id { get; set; }
        public int addedon { get; set; }
        public int addedby { get; set; }
        public int blocked_till { get; set; }
        public int blocked_by { get; set; }
        public string custom_provider { get; set; }
        public string good_src { get; set; }
        public string comment { get; set; }
    }
}
