//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aleks_daspecs_linestbl_old
    {
        public int spec_id { get; set; }
        public int line_id { get; set; }
        public string mark { get; set; }
        public string number { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int count { get; set; }
        public decimal compare_cost { get; set; }
        public string units { get; set; }
        public string comment { get; set; }
        public string empty_line_comment { get; set; }
        public string additional_info { get; set; }
        public byte is_wrong { get; set; }
        public byte is_infoblock { get; set; }
    }
}
