//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aleks_daspecs_accounts
    {
        public long id { get; set; }
        public long linestbl_id { get; set; }
        public long line_id { get; set; }
        public long spec_id { get; set; }
        public long account_id { get; set; }
        public long category_id { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual aleks_daspecs_linestbl aleks_daspecs_linestbl { get; set; }
    }
}
