//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aleks_daspecs_bills
    {
        public long id { get; set; }
        public long spec_id { get; set; }
        public long user_id { get; set; }
        public int opdate { get; set; }
        public string bill_code { get; set; }
        public string legal_code { get; set; }
        public string customer_inn { get; set; }
        public long vat { get; set; }
        public long prepay { get; set; }
        public byte is_export { get; set; }
        public string bill_image { get; set; }
        public string status { get; set; }
        public string status_description { get; set; }
        public byte deleted { get; set; }
        public string title_source { get; set; }
    }
}
