//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aleks_daspecs_maintbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aleks_daspecs_maintbl()
        {
            this.C100tx_FindCategory = new HashSet<C100tx_FindCategory>();
        }
    
        public long id { get; set; }
        public int parent { get; set; }
        public string uniq_title { get; set; }
        public string real_title { get; set; }
        public string alias { get; set; }
        public string description { get; set; }
        public string bottom_description { get; set; }
        public string legal_company { get; set; }
        public byte is_export { get; set; }
        public int date { get; set; }
        public int user_id { get; set; }
        public int chked { get; set; }
        public string status { get; set; }
        public string note { get; set; }
        public string serial_session { get; set; }
        public int shop_date { get; set; }
        public int delivery { get; set; }
        public Nullable<int> customer_bid { get; set; }
        public string customer_inn { get; set; }
        public string customer_name { get; set; }
        public string deploy_object { get; set; }
        public Nullable<int> deal_bid { get; set; }
        public string deal_name { get; set; }
        public string head_mail { get; set; }
        public string mrk_mail { get; set; }
        public string seller_mail { get; set; }
        public string customer_contacts { get; set; }
        public byte deleted { get; set; }
        public byte is_public { get; set; }
        public byte is_cart { get; set; }
        public byte is_opened_to_provider { get; set; }
        public string user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C100tx_FindCategory> C100tx_FindCategory { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
