//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aleks_provider_info
    {
        public long id { get; set; }
        public string pagetitle { get; set; }
        public string longtitle { get; set; }
        public string description { get; set; }
        public string inn { get; set; }
        public string img { get; set; }
        public string site { get; set; }
        public Nullable<int> discount { get; set; }
        public string tax_system { get; set; }
        public Nullable<long> min_purchase { get; set; }
        public string min_purchase_currency { get; set; }
        public Nullable<long> delivery_time_from { get; set; }
        public Nullable<long> delivery_time_to { get; set; }
        public Nullable<int> prepay { get; set; }
        public Nullable<long> pay_deferment_from { get; set; }
        public Nullable<long> pay_deferment_to { get; set; }
        public Nullable<long> price_update { get; set; }
        public Nullable<long> rating { get; set; }
        public string agreement_type { get; set; }
        public Nullable<long> agreement_deferment { get; set; }
        public Nullable<byte> on_moderate { get; set; }
    }
}
