//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aleks_provider_info_old
    {
        public Nullable<int> id { get; set; }
        public string pagetitle { get; set; }
        public string longtitle { get; set; }
        public string description { get; set; }
        public string inn { get; set; }
        public string img { get; set; }
        public string site { get; set; }
        public int discount { get; set; }
        public string tax_system { get; set; }
        public int min_purchase { get; set; }
        public string min_purchase_currency { get; set; }
        public int delivery_time_from { get; set; }
        public int delivery_time_to { get; set; }
        public int prepay { get; set; }
        public int pay_deferment_from { get; set; }
        public int pay_deferment_to { get; set; }
        public int price_update { get; set; }
        public int rating { get; set; }
        public string agreement_type { get; set; }
        public int agreement_deferment { get; set; }
        public byte on_moderate { get; set; }
    }
}
