//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aleks_daspecs_accessrules
    {
        public int spec_id { get; set; }
        public int user_id { get; set; }
        public string permission { get; set; }
        public int createdon { get; set; }
        public int createdby { get; set; }
    }
}
