//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aleks_goods_colors
    {
        public int cid { get; set; }
        public int resid { get; set; }
        public int opdate { get; set; }
        public string img { get; set; }
        public string price { get; set; }
        public int is_default { get; set; }
    }
}
