//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aleks_goods_prices
    {
        public long good_id { get; set; }
        public long in_price { get; set; }
        public string currency { get; set; }
        public long discount { get; set; }
        public long markup { get; set; }
        public byte has_vat { get; set; }
        public long vat { get; set; }
        public long custom_vat_changing { get; set; }
        public int deployment_rate { get; set; }
        public int delivery_warehouse_rate { get; set; }
        public int delivery_client_rate { get; set; }
        public long opdate { get; set; }
        public byte is_auto_recount { get; set; }
    }
}
