//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aleks_goods_params
    {
        public string parametr { get; set; }
        public int good_id { get; set; }
        public string value { get; set; }
        public string unit { get; set; }
        public byte is_kit { get; set; }
        public int cprice { get; set; }
    }
}
