//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRolesMenus
    {
        public int Id { get; set; }
        public string RoleId { get; set; }
        public string MenuId { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
    }
}
