//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public long id { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<decimal> Summ { get; set; }
        public Nullable<int> TypeId { get; set; }
        public System.DateTime Date { get; set; }
        public string UserId { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual BalanceTypeHB BalanceTypeHB { get; set; }
    }
}
