//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetails
    {
        public int Id { get; set; }
        public string CheckingAccount { get; set; }
        public string BenefeciaryBankName { get; set; }
        public string CorrespondingAccountOfBank { get; set; }
        public string BIC { get; set; }
        public string KPP { get; set; }
        public string KBK { get; set; }
    }
}
