//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C100tx_PlanPositions
    {
        public long id { get; set; }
        public string uid { get; set; }
        public Nullable<int> number { get; set; }
        public string type { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string characteristic { get; set; }
        public Nullable<bool> volumeIs { get; set; }
        public Nullable<int> volumeCurrent { get; set; }
        public Nullable<int> volume1 { get; set; }
        public Nullable<int> volume2 { get; set; }
        public Nullable<int> volumeLast { get; set; }
        public Nullable<int> volumeAll { get; set; }
        public Nullable<int> costAverage { get; set; }
        public Nullable<int> summCurrent { get; set; }
        public Nullable<int> summ1 { get; set; }
        public Nullable<int> summ2 { get; set; }
        public Nullable<int> summLast { get; set; }
        public Nullable<int> summAll { get; set; }
        public Nullable<int> costStart { get; set; }
        public Nullable<int> Account { get; set; }
        public Nullable<int> plan { get; set; }
        public string revision { get; set; }
        public string file { get; set; }
    
        public virtual C100tx_plans C100tx_plans { get; set; }
    }
}
