//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C100tx_Regions
    {
        public int id { get; set; }
        public string oktmoId { get; set; }
        public string oktmoCode { get; set; }
        public string name { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<int> headerId { get; set; }
    
        public virtual C100tx_RegionsHeaders C100tx_RegionsHeaders { get; set; }
    }
}
