//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C100tx_plans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C100tx_plans()
        {
            this.C100tx_PlanPositions = new HashSet<C100tx_PlanPositions>();
        }
    
        public int id { get; set; }
        public string plan_purchase { get; set; }
        public string plan_shedule { get; set; }
        public string year_shedule { get; set; }
        public string date_approval { get; set; }
        public string date_shedule_change { get; set; }
        public string date_approval_rationale { get; set; }
        public string date_public { get; set; }
        public string status { get; set; }
        public Nullable<long> account { get; set; }
        public Nullable<System.DateTime> dateadd { get; set; }
        public Nullable<int> region { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C100tx_PlanPositions> C100tx_PlanPositions { get; set; }
        public virtual Accounts Accounts { get; set; }
    }
}
