//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C100tx_OrdersStatusHistory
    {
        public long id { get; set; }
        public long spec_id { get; set; }
        public long prov_id { get; set; }
        public int status_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual C100tx_OrdersStatuses C100tx_OrdersStatuses { get; set; }
    }
}
