//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C100tx_FindCategory
    {
        public long id { get; set; }
        public long spec_id { get; set; }
        public long line_id { get; set; }
        public int category_id { get; set; }
        public Nullable<bool> is_checked { get; set; }
    
        public virtual aleks_daspecs_maintbl aleks_daspecs_maintbl { get; set; }
        public virtual catalog_categories catalog_categories { get; set; }
    }
}
