//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_tags
    {
        public int item_id { get; set; }
        public string item_type { get; set; }
        public string tag_word { get; set; }
        public decimal weight { get; set; }
        public string source { get; set; }
    }
}
