//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog_categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalog_categories()
        {
            this.C100tx_FindCategory = new HashSet<C100tx_FindCategory>();
            this.Accounts_Categories = new HashSet<Accounts_Categories>();
        }
    
        public int id { get; set; }
        public string pagetitle { get; set; }
        public string longtitle { get; set; }
        public string alias { get; set; }
        public string description { get; set; }
        public string content { get; set; }
        public int parent { get; set; }
        public int editedon { get; set; }
        public int editedby { get; set; }
        public int createdon { get; set; }
        public int createdby { get; set; }
        public byte deleted { get; set; }
        public byte is_service { get; set; }
        public string okpd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C100tx_FindCategory> C100tx_FindCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounts_Categories> Accounts_Categories { get; set; }
    }
}
