//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents_Templates
    {
        public int id { get; set; }
        public string name_template { get; set; }
        public byte[] bytestream { get; set; }
        public Nullable<int> type_template_id { get; set; }
        public Nullable<int> account_role_id { get; set; }
        public Nullable<bool> current_version { get; set; }
    }
}
