//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_StatusLog
    {
        public int id { get; set; }
        public string email { get; set; }
        public string message_id { get; set; }
        public string @event { get; set; }
        public byte[] timestamp { get; set; }
    }
}
