//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Files()
        {
            this.Message_File = new HashSet<Message_File>();
        }
    
        public string Id { get; set; }
        public Nullable<int> idtable { get; set; }
        public Nullable<int> typetable { get; set; }
        public string userId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string filename { get; set; }
        public byte[] filedata { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Type_Table Type_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message_File> Message_File { get; set; }
    }
}
