//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratedDocument
    {
        public int Id { get; set; }
        public string NameDocument { get; set; }
        public Nullable<int> NumberDocument { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> NameTypeId { get; set; }
        public Nullable<long> Account { get; set; }
        public Nullable<bool> IsFromAdmin { get; set; }
        public byte[] bytebuffer { get; set; }
    }
}
