//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Help_Comments
    {
        public int ID_Comments { get; set; }
        public string Text { get; set; }
        public Nullable<int> ID_Content { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual Help_Content Help_Content { get; set; }
    }
}
