//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Help_Roles
    {
        public string id { get; set; }
        public Nullable<int> Id_categories { get; set; }
        public Nullable<int> Id_content { get; set; }
        public Nullable<int> Accounts_RoleId { get; set; }
        public string RoleId { get; set; }
    
        public virtual Accounts_RolesHB Accounts_RolesHB { get; set; }
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual Help_Categories Help_Categories { get; set; }
        public virtual Help_Content Help_Content { get; set; }
    }
}
