//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Pattern_User_Entiity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Log_Pattern_User_Entiity()
        {
            this.Log_Pattern_To_Users = new HashSet<Log_Pattern_To_Users>();
        }
    
        public int Id { get; set; }
        public Nullable<int> tupetable { get; set; }
        public string name { get; set; }
        public string nameFild { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log_Pattern_To_Users> Log_Pattern_To_Users { get; set; }
    }
}
