//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Pattern_To_Users
    {
        public int Id { get; set; }
        public Nullable<int> paternId { get; set; }
        public string userId { get; set; }
        public Nullable<int> idUserEntity { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Log_Pattern Log_Pattern { get; set; }
        public virtual Log_Pattern_User_Entiity Log_Pattern_User_Entiity { get; set; }
        public virtual Type_Table Type_Table { get; set; }
    }
}
