//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_PropertySaveTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Log_PropertySaveTable()
        {
            this.Log_Pattern = new HashSet<Log_Pattern>();
        }
    
        public int Id { get; set; }
        public Nullable<int> idTypeTable { get; set; }
        public string name { get; set; }
        public string FirstNameFild { get; set; }
        public string SecondNameField { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log_Pattern> Log_Pattern { get; set; }
        public virtual Type_Table Type_Table { get; set; }
    }
}
