//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs_Messages
    {
        public System.Guid id { get; set; }
        public long logId { get; set; }
        public string messageId { get; set; }
        public int messagesCount { get; set; }
    
        public virtual Logs Logs { get; set; }
    }
}
