//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Logs()
        {
            this.Logs_Messages = new HashSet<Logs_Messages>();
        }
    
        public long id { get; set; }
        public int logType { get; set; }
        public long accountId { get; set; }
        public string content { get; set; }
        public System.DateTime date { get; set; }
        public string userId { get; set; }
        public string json { get; set; }
        public Nullable<int> actionId { get; set; }
        public Nullable<int> typetable { get; set; }
        public Nullable<int> idtable { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Logs_Types Logs_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Logs_Messages> Logs_Messages { get; set; }
    }
}
