//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Roles
    {
        public string id { get; set; }
        public Nullable<int> Id_categories { get; set; }
        public Nullable<int> Id_item { get; set; }
        public int Accounts_RoleId { get; set; }
        public string RoleId { get; set; }
        public Nullable<int> Position { get; set; }
    
        public virtual Accounts_RolesHB Accounts_RolesHB { get; set; }
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual Menu_Category Menu_Category { get; set; }
        public virtual Menu_Items Menu_Items { get; set; }
    }
}
