//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Constructor_Roles
    {
        public int id { get; set; }
        public int id_Accounts_Roles { get; set; }
        public string id_Users_Roles { get; set; }
        public int id_Layout { get; set; }
    
        public virtual Accounts_RolesHB Accounts_RolesHB { get; set; }
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual Menu_Constructor_Layout Menu_Constructor_Layout { get; set; }
    }
}
