//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long id { get; set; }
        public long accountId { get; set; }
        public string userId { get; set; }
        public string content { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<long> spec_id { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
