//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parse
    {
        public int id { get; set; }
        public string PlanNumber { get; set; }
        public string PlanInfo_id { get; set; }
        public string Agency_id { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Law { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public string PlanId { get; set; }
    }
}
