//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public System.Guid id { get; set; }
        public long accountId { get; set; }
        public int operationType { get; set; }
        public decimal sum { get; set; }
        public decimal balance { get; set; }
        public System.DateTime date { get; set; }
        public string description { get; set; }
    
        public virtual Accounts Accounts { get; set; }
    }
}
