//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrjPreferences
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrjPreferences()
        {
            this.PrjPreferences1 = new HashSet<PrjPreferences>();
            this.PrjSettings_Data = new HashSet<PrjSettings_Data>();
            this.StatisticLeftMenu = new HashSet<StatisticLeftMenu>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> typedata_id { get; set; }
        public string description { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public Nullable<int> setting_id { get; set; }
        public Nullable<int> display_order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrjPreferences> PrjPreferences1 { get; set; }
        public virtual PrjPreferences PrjPreferences2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrjSettings_Data> PrjSettings_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatisticLeftMenu> StatisticLeftMenu { get; set; }
    }
}
