//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrjPhoneNumbers
    {
        public int id { get; set; }
        public string phone_number { get; set; }
        public Nullable<int> settings_data_id { get; set; }
        public string phone_type { get; set; }
        public string name { get; set; }
        public Nullable<int> telecom_operator_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string ip_address { get; set; }
        public string domain_name { get; set; }
        public Nullable<int> line_count { get; set; }
        public Nullable<int> in_line_count { get; set; }
        public Nullable<int> out_line_count { get; set; }
        public Nullable<int> projects_id { get; set; }
    
        public virtual PrjSettings_Data PrjSettings_Data { get; set; }
        public virtual PrjTelecomOperators PrjTelecomOperators { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
