//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.PrjSettings_Data = new HashSet<PrjSettings_Data>();
            this.Projects_Services = new HashSet<Projects_Services>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public long accountId { get; set; }
        public string oktellCode { get; set; }
        public string guid { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<System.DateTime> date_last_edit { get; set; }
        public Nullable<System.Guid> TypeId { get; set; }
        public string creatorId { get; set; }
        public string ownerId { get; set; }
        public string description { get; set; }
        public int statusesId { get; set; }
        public Nullable<bool> isExternal { get; set; }
        public bool deleted { get; set; }
        public System.DateTime endDate { get; set; }
        public System.DateTime startDate { get; set; }
        public int type { get; set; }
        public string avatar { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrjSettings_Data> PrjSettings_Data { get; set; }
        public virtual ProjectTypes ProjectTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projects_Services> Projects_Services { get; set; }
    }
}
