//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Type_Setting
    {
        public int id { get; set; }
        public int typeid { get; set; }
        public int settingid { get; set; }
    
        public virtual Project_Settings Project_Settings { get; set; }
        public virtual Project_Types Project_Types { get; set; }
    }
}
