//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Types_User
    {
        public int id { get; set; }
        public Nullable<int> typeid { get; set; }
        public string userid { get; set; }
        public Nullable<int> projectid { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Project_Types Project_Types { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual Projects Projects1 { get; set; }
    }
}
