//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedSpecifications
    {
        public int Id { get; set; }
        public Nullable<long> Account { get; set; }
        public Nullable<long> Specification { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> NumberCchet { get; set; }
        public Nullable<long> BalanceId { get; set; }
    }
}
