//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id { get; set; }
        public string header { get; set; }
        public string body { get; set; }
        public long accountId { get; set; }
        public string userId { get; set; }
        public int typeId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Request_Types_HB Request_Types_HB { get; set; }
    }
}
