//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_Data
    {
        public int id { get; set; }
        public Nullable<int> project_serviceId { get; set; }
        public Nullable<int> preferenceId { get; set; }
        public string preferenceValue { get; set; }
    
        public virtual Projects_Services Projects_Services { get; set; }
        public virtual Services_Preferences_HB Services_Preferences_HB { get; set; }
    }
}
