//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_Prices
    {
        public int id { get; set; }
        public int serviceId { get; set; }
        public int priceTypesId { get; set; }
        public Nullable<int> tarifId { get; set; }
        public Nullable<int> preferenceId { get; set; }
        public Nullable<int> value { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_stop { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual Price_TypesHB Price_TypesHB { get; set; }
        public virtual Services Services { get; set; }
        public virtual Services_Preferences_HB Services_Preferences_HB { get; set; }
        public virtual Tarifs Tarifs { get; set; }
    }
}
