//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic_oktell
    {
        public int id { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<System.DateTime> TimeAnswer { get; set; }
        public Nullable<System.DateTime> TimeStop { get; set; }
        public Nullable<int> TimeWaiting { get; set; }
        public Nullable<int> TimeTalking { get; set; }
        public string LineNumber { get; set; }
        public string Operator { get; set; }
        public string SubscriberNumber { get; set; }
        public string direction { get; set; }
        public string project { get; set; }
    }
}
