//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticLeftMenus
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> display_order { get; set; }
        public Nullable<int> project_setting_id { get; set; }
        public string action_name { get; set; }
        public string icon_name { get; set; }
    }
}
