//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusSign
    {
        public int id { get; set; }
        public Nullable<int> document_templates_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<long> account_id { get; set; }
        public string user_id { get; set; }
    }
}
