//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic_pbx
    {
        public int id { get; set; }
        public string UNIQUEID { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> answer { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public string src_chan { get; set; }
        public string src_num { get; set; }
        public string dst_chan { get; set; }
        public string dst_num { get; set; }
        public string linkedid { get; set; }
        public string did { get; set; }
        public string disposition { get; set; }
        public string recordingfile { get; set; }
        public string from_account { get; set; }
        public string to_account { get; set; }
        public string dialstatus { get; set; }
        public string appname { get; set; }
        public string transfer { get; set; }
        public string is_app { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> billsec { get; set; }
        public string work_completed { get; set; }
    }
}
