//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Data
    {
        public int id { get; set; }
        public Nullable<int> rowId { get; set; }
        public string value { get; set; }
        public Nullable<int> columnId { get; set; }
    
        public virtual Table_Columns Table_Columns { get; set; }
        public virtual Table_Rows Table_Rows { get; set; }
    }
}
