//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifs_Data
    {
        public int id { get; set; }
        public int value { get; set; }
        public int count { get; set; }
        public int tarifId { get; set; }
    
        public virtual Tarifs Tarifs { get; set; }
    }
}
