//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Status_History
    {
        public int id { get; set; }
        public int tasksId { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<System.DateTime> chanageDate { get; set; }
        public string userId { get; set; }
        public Nullable<int> personalStatusId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Task_Personal_Statuses Task_Personal_Statuses { get; set; }
        public virtual Task_Projects_Statuses Task_Projects_Statuses { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
