//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Checks
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> ordering { get; set; }
        public int tasksId { get; set; }
    
        public virtual Tasks Tasks { get; set; }
    }
}
