//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatesKP
    {
        public int id { get; set; }
        public byte[] bytestream { get; set; }
        public Nullable<int> typefile_id { get; set; }
        public string NameTemplate { get; set; }
        public string userid { get; set; }
        public Nullable<bool> standart { get; set; }
    
        public virtual TypeFileKP TypeFileKP { get; set; }
    }
}
